# Generated by Django 3.1.7 on 2021-04-30 03:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210429_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='uuid',
            field=models.CharField(default=uuid.UUID('67db417a-6ec2-420b-8363-a88b2b530865'), max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='uuid',
            field=models.CharField(default=uuid.UUID('2fbe3880-2ea8-4034-bf35-3b5bff2284e2'), max_length=64, unique=True),
        ),
    ]
