# Generated by Django 3.1.7 on 2021-04-30 05:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210430_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='uuid',
            field=models.CharField(default=uuid.UUID('537e7211-510d-4ba8-bd77-17d0e0f4b35f'), max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='uuid',
            field=models.CharField(default=uuid.UUID('83151e84-4b5c-4957-a6c4-2ddd8c18f398'), max_length=64, unique=True),
        ),
    ]
